version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: app_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./BACKEND/mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=sistema-consultas

  backend:
    build: ./BACKEND
    container_name: app_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/sistema-consultas
      - JWT_SECRET=UnaPalabraClaveSuperSecretaYMasiva2026!
      - JWT_EXPIRE=24h
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  frontend:
    build: ./FRONTEND
    container_name: app_frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - INTERNAL_API_URL=http://backend:5000
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  mongo_data: